-- ==============================================================================
-- PROJETO: Analytics Educação Básica (INEP)
-- ETAPA: Carga de Dados Históricos - ESCOPO NACIONAL (2019 a 2024)
-- ARQUIVO: 06_carga_historica_2019_2024.sql
-- ==============================================================================

USE Educacao_Analytics;
GO

PRINT '======================================================================';
PRINT '    INICIANDO UNIFICAÇÃO E CARGA HISTÓRICA NACIONAL (2019 - 2024)     ';
PRINT '======================================================================';
PRINT '';

-- Limpeza preventiva para garantir idempotência
DELETE FROM dbo.fato_censo_escolar WHERE NU_ANO_CENSO BETWEEN 2019 AND 2024;
PRINT '♻️ Registros antigos de 2019 a 2024 limpos por segurança.';
PRINT '';

PRINT '🚀 Injetando dados unificados do BRASIL INTEIRO na Fato...';
PRINT '     (Esta operação pode levar de 1 a 2 minutos devido ao volume de dados)';

INSERT INTO dbo.fato_censo_escolar (
    NU_ANO_CENSO, CO_ENTIDADE, NO_ENTIDADE, CO_MUNICIPIO, TP_DEPENDENCIA,
    QT_MAT_BAS, QT_DOC_BAS, IN_INTERNET, IN_BANDA_LARGA, 
    IN_LABORATORIO_INFORMATICA, IN_BIBLIOTECA, IN_AGUA_POTAVEL, 
    IN_ENERGIA_INEXISTENTE, IN_ESGOTO_INEXISTENTE
)
SELECT 
    NU_ANO_CENSO, 
    CAST(CO_ENTIDADE AS BIGINT), 
    CAST(NO_ENTIDADE AS VARCHAR(150)), 
    CAST(CO_MUNICIPIO AS INT), 
    CAST(TP_DEPENDENCIA AS INT),
    CAST(QT_MAT_BAS AS INT), 
    CAST(QT_DOC_BAS AS INT), 
    CAST(IN_INTERNET AS INT), 
    CAST(IN_BANDA_LARGA AS INT),
    CAST(IN_LABORATORIO_INFORMATICA AS INT), 
    CAST(IN_BIBLIOTECA AS INT), 
    CAST(IN_AGUA_POTAVEL AS INT),
    CASE WHEN IN_ENERGIA_INEXISTENTE = 1 THEN 1 ELSE 0 END,
    CASE WHEN IN_ESGOTO_INEXISTENTE = 1 THEN 1 ELSE 0 END
FROM (
    SELECT NU_ANO_CENSO, CO_ENTIDADE, NO_ENTIDADE, CO_MUNICIPIO, TP_DEPENDENCIA, QT_MAT_BAS, QT_DOC_BAS, IN_INTERNET, IN_BANDA_LARGA, IN_LABORATORIO_INFORMATICA, IN_BIBLIOTECA, IN_AGUA_POTAVEL, IN_ENERGIA_INEXISTENTE, IN_ESGOTO_INEXISTENTE FROM dbo.microdados_ed_basica_2019 UNION ALL
    SELECT NU_ANO_CENSO, CO_ENTIDADE, NO_ENTIDADE, CO_MUNICIPIO, TP_DEPENDENCIA, QT_MAT_BAS, QT_DOC_BAS, IN_INTERNET, IN_BANDA_LARGA, IN_LABORATORIO_INFORMATICA, IN_BIBLIOTECA, IN_AGUA_POTAVEL, IN_ENERGIA_INEXISTENTE, IN_ESGOTO_INEXISTENTE FROM dbo.microdados_ed_basica_2020 UNION ALL
    SELECT NU_ANO_CENSO, CO_ENTIDADE, NO_ENTIDADE, CO_MUNICIPIO, TP_DEPENDENCIA, QT_MAT_BAS, QT_DOC_BAS, IN_INTERNET, IN_BANDA_LARGA, IN_LABORATORIO_INFORMATICA, IN_BIBLIOTECA, IN_AGUA_POTAVEL, IN_ENERGIA_INEXISTENTE, IN_ESGOTO_INEXISTENTE FROM dbo.microdados_ed_basica_2021 UNION ALL
    SELECT NU_ANO_CENSO, CO_ENTIDADE, NO_ENTIDADE, CO_MUNICIPIO, TP_DEPENDENCIA, QT_MAT_BAS, QT_DOC_BAS, IN_INTERNET, IN_BANDA_LARGA, IN_LABORATORIO_INFORMATICA, IN_BIBLIOTECA, IN_AGUA_POTAVEL, IN_ENERGIA_INEXISTENTE, IN_ESGOTO_INEXISTENTE FROM dbo.microdados_ed_basica_2022 UNION ALL
    SELECT NU_ANO_CENSO, CO_ENTIDADE, NO_ENTIDADE, CO_MUNICIPIO, TP_DEPENDENCIA, QT_MAT_BAS, QT_DOC_BAS, IN_INTERNET, IN_BANDA_LARGA, IN_LABORATORIO_INFORMATICA, IN_BIBLIOTECA, IN_AGUA_POTAVEL, IN_ENERGIA_INEXISTENTE, IN_ESGOTO_INEXISTENTE FROM dbo.microdados_ed_basica_2023 UNION ALL
    SELECT NU_ANO_CENSO, CO_ENTIDADE, NO_ENTIDADE, CO_MUNICIPIO, TP_DEPENDENCIA, QT_MAT_BAS, QT_DOC_BAS, IN_INTERNET, IN_BANDA_LARGA, IN_LABORATORIO_INFORMATICA, IN_BIBLIOTECA, IN_AGUA_POTAVEL, IN_ENERGIA_INEXISTENTE, IN_ESGOTO_INEXISTENTE FROM dbo.microdados_ed_basica_2024
) AS brasil_historico
WHERE TP_DEPENDENCIA IN (2, 3); -- Mantém o foco analítico nas redes Pública Estadual e Municipal
GO

-- Validação rápida da volumetria nacional
PRINT '';
PRINT '📊 Resumo da carga histórica nacional por ano:';
SELECT 
    NU_ANO_CENSO AS Ano,
    COUNT(*) AS Total_Escolas_Brasil,
    SUM(QT_MAT_BAS) AS Total_Matriculas_Brasil
FROM dbo.fato_censo_escolar
WHERE NU_ANO_CENSO BETWEEN 2019 AND 2024
GROUP BY NU_ANO_CENSO
ORDER BY NU_ANO_CENSO DESC;
GO

PRINT '======================================================================';
PRINT '        CARGA HISTÓRICA NACIONAL CONCLUÍDA COM SUCESSO                ';
PRINT '======================================================================';
GO